# -*- coding: utf-8 -*-
"""Bakes the written missions and the street crowd into the mockup.

    python scripts/game_bake.py                       # content repo beside this one
    python scripts/game_bake.py --content ../fluidez-es-ni

The missions live in `scenicprints/fluidez-es-ni` because they are content and
they ship in the pack the app downloads. The mockup lives here and has to stay
ONE file you can open in a browser with no build and no server, so it cannot
fetch them: they get baked in.

WHERE PEOPLE STAND. The missions do not carry coordinates and should not --
they are written against a district, not against a tile, and a tile number
would rot the moment the map is rebuilt at a different scale. So placement
lives here, as a real named place plus an offset in tiles, and the named
places come out of the OSM extract. Anything without an entry is dropped near
its district anchor AND REPORTED, because a mission that quietly piles up on
top of another one is a mission nobody will find.
"""
import argparse, io, json, os, sys, zlib

NL = chr(10)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HTML = os.path.join(ROOT, 'mockups', 'granada.html')

BEGIN = u'/* ══ MISSIONS — generated by scripts/game_bake.py, do not edit ══ */'
END = u'/* ══ end missions ══ */'

# Every district's anchor. This is where the STREET CROWD for that district
# stands -- world.js places them round it -- and it is the fallback for a
# mission with no placement of its own. So it has to be where the district
# actually is, or the people who point you at a mission are nowhere near it.
#
# Three of these used to be wrong and nothing said so. `Isla El Castillo` and
# `Barrio Posintepe` are not in the OSM extract at all, so they resolved to
# nothing and fell back to Parque Central; `Plaza la Fuente` is in the middle of
# town while every Malecon mission is out at the Centro Turistico. The result
# was hint-givers standing 1.0 to 1.3 km from the missions they were pointing
# at -- in a different district, across the city. game.test.mjs now fails if a
# name here does not resolve, and if a district's crowd drifts away from its
# own missions.
DISTRICT = {
    'centro': u'Parque Central', 'mercado': u'Mercado Municipal',
    'xalteva': u'Iglesia de Xalteva', 'guadalupe': u'Iglesia de Nuestra Se\xf1ora de Guadalupe',
    'terminal': u'Transnica & King Quality', 'trabajo': u'Estadio Roque Tadeo Zavala',
    'tramites': u'Hospital Granada', 'fiestas': u'Parroquia Nuestra Se\xf1ora del Socorro',
    'barrio': u'Parque Otra Banda', 'pantanal': u'Reparto Germ\xe1n Pomares',
    'malecon': u'Centro Turistico', 'afuera': u'Camino a la Laguna',
}

# How far a district's people spread out from its anchor, as a multiplier on
# the offsets below.
#
# Kevin: "Spread out the people so the quests arent so concentrated." He was
# right: nine of the twelve districts hung every mission off a single named
# place with offsets inside about seventy metres, which is one screenful. You
# walked into a knot of people and then had several hundred metres of nothing.
# These widen a district to roughly two or three hundred metres -- a few blocks
# you walk THROUGH rather than a dot you stand on.
#
# They are not all the same because the ground is not. Malecon runs along the
# water and Afuera along one road out of town, so pushing those out hard just
# presses people against the shore or the verge; El Centro, Las fiestas and
# Pantanal were already spread over real separate landmarks and need less.
SPREAD = {
    'centro': 1.7, 'mercado': 2.6, 'xalteva': 1.8, 'guadalupe': 2.8,
    'terminal': 2.4, 'trabajo': 2.8, 'tramites': 2.6, 'fiestas': 1.8,
    'barrio': 2.6, 'pantanal': 1.6, 'malecon': 1.7, 'afuera': 1.8,
}


def spread_of(mid):
    return SPREAD.get(str(mid).split('-')[0], 2.0)


def widen(mid, dx, dy):
    """Push an offset out from its anchor by its district's spread.

    Scaling rather than re-authoring keeps every arrangement the offsets
    already describe -- the hostel stays a block west and south of the plaza,
    it is just further west and further south. Placement is snapped to a
    walkable, reachable, unoccupied tile at runtime, so a widened offset that
    lands in a block ends up in the nearest street rather than in a wall.
    """
    f = spread_of(mid)
    return int(round(dx * f)), int(round(dy * f))

# mission id -> (named place, dx, dy, vehicle or None)
# Read these as: the hostel is a block west and south of the plaza; the
# comedor and the waiter are down La Calzada, which runs east from the
# cathedral to the water; the cuidacarros is on the corner with a moto parked
# beside him, because that is what he is watching.
PLACE = {
    'centro-01': (u'Parque Central', -14, 8, None),
    'centro-02': (u'Catedral', 12, 4, None),
    'centro-03': (u'Catedral', 24, 3, None),
    'centro-04': (u'Parque Central', 3, -4, None),
    'centro-05': (u'Palacio Municipal', 6, 7, 'moto'),
    'centro-06': (u'Catedral', 0, 7, None),
    'centro-07': (u'Palacio Municipal', -9, 2, None),
    'centro-08': (u'Parque Central', 11, 9, None),
    'centro-09': (u'Plaza la Fuente', -5, 4, None),
    'centro-10': (u'Parque Central', -4, -7, None),
    'centro-11': (u'Plazuela de los Leones', 4, 6, None),
    'centro-12': (u'Parque Central', 8, -2, None),
    # El Mercado. The market building itself is a solid block of awning, so
    # these sit in the streets and doorways around it, which is where the
    # stalls really spill out to.
    'mercado-01': (u'Mercado Municipal', -7, 4, None),
    'mercado-02': (u'Mercado Municipal', 9, -7, None),
    'mercado-03': (u'Mercado Municipal', 4, 6, None),
    'mercado-04': (u'Mercado Municipal', -5, 9, None),
    'mercado-05': (u'Mercado Municipal', 11, 7, None),
    'mercado-06': (u'Mercado Municipal', -10, -4, None),
    'mercado-07': (u'Mercado Municipal', 6, -8, None),
    'mercado-08': (u'Mercado Municipal', -3, -10, None),
    'mercado-09': (u'Mercado Municipal', 8, 10, None),
    'mercado-10': (u'Mercado Municipal', -9, 8, None),
    'mercado-11': (u'Supermercado Pal\xed Granada', 3, 5, None),
    'mercado-12': (u'Mercado Municipal', 13, 2, None),
    # Xalteva, the old quarter west of the centre. The sacristan and the beata
    # are at the church door, the cemetery keeper is at the cemetery, and the
    # historian is beside the walls he is talking about.
    'xalteva-01': (u'Plaza Xalteva', -5, 6, None),
    'xalteva-02': (u'Iglesia de Xalteva', 0, 6, None),
    'xalteva-03': (u'Iglesia de Xalteva', 6, 8, None),
    'xalteva-04': (u'Plaza Xalteva', 9, -5, None),
    'xalteva-05': (u'Plaza Xalteva', -11, -3, None),
    'xalteva-06': (u'Plaza Xalteva', 7, 10, 'bici'),
    'xalteva-07': (u'Fortaleza La Polvora', 11, 8, None),
    'xalteva-08': (u'Cementerio Municipal de Granada', 2, -7, None),
    'xalteva-09': (u'Iglesia de Xalteva', -8, 4, None),
    'xalteva-10': (u'Fortaleza La Polvora', 5, -4, None),
    # Guadalupe, sloping east towards the water, around its church.
    'guadalupe-01': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', -9, 5, None),
    'guadalupe-02': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', 10, 7, 'moto'),
    'guadalupe-03': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', -6, -9, None),
    'guadalupe-04': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', 6, -7, None),
    'guadalupe-05': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', -12, -2, None),
    'guadalupe-06': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', 3, 11, None),
    'guadalupe-07': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', 12, -3, None),
    'guadalupe-08': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', -3, 9, None),
    'guadalupe-09': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', 9, 13, None),
    'guadalupe-10': (u'Iglesia de Nuestra Se\xf1ora de Guadalupe', -10, 12, None),
    # Pantanal, down towards the water. The fisherman stands at the lakefront
    # with his lancha; the rest are in the barrio behind it.
    'pantanal-01': (u'Centro Turistico', 6, 4, 'lancha'),
    'pantanal-02': (u'Reparto Germ\xe1n Pomares', -6, 4, None),
    'pantanal-03': (u'Reparto Germ\xe1n Pomares', 7, -5, None),
    'pantanal-04': (u'Reparto Germ\xe1n Pomares', -9, -3, None),
    'pantanal-05': (u'Reparto Germ\xe1n Pomares', 3, 8, None),
    'pantanal-06': (u'Carlos M. Marenco', -5, 6, None),
    'pantanal-07': (u'Carlos M. Marenco', 8, -4, None),
    'pantanal-08': (u'Carlos M. Marenco', -8, -6, None),
    'pantanal-09': (u'Reparto Germ\xe1n Pomares', 11, 7, None),
    'pantanal-10': (u'Carlos M. Marenco', 4, 10, None),
    # La Terminal. Six of these happen at a vehicle, which is the point of it.
    #
    # All ten stand at ONE terminal now. They used to be split between Transnica
    # and the UCA microbus stop, which are 1.1 km apart on opposite sides of
    # town -- so the district had no middle, and the arrow pointed at the
    # average of the two, which lands in Tu barrio. Both are real places, but a
    # cobrador, a ticket window, a taxista and somebody seeing a relative off
    # belong at the same terminal, and nothing in the missions says otherwise.
    'terminal-01': (u'Transnica & King Quality', -4, 5, 'bus'),
    'terminal-02': (u'Transnica & King Quality', 6, 5, 'taxi'),
    'terminal-03': (u'Transnica & King Quality', -6, 7, 'taxi'),
    'terminal-04': (u'Transnica & King Quality', 2, -6, None),
    'terminal-05': (u'Transnica & King Quality', 13, -2, 'bus'),
    'terminal-06': (u'Transnica & King Quality', -9, -3, None),
    'terminal-07': (u'Transnica & King Quality', 9, -7, None),
    'terminal-08': (u'Transnica & King Quality', -12, 4, None),
    'terminal-09': (u'Transnica & King Quality', 11, 2, 'bus'),
    'terminal-10': (u'Transnica & King Quality', 3, 12, None),
    # Tu barrio: your own street, around Parque Otra Banda. Doña Marta's
    # house is the anchor of the district and three missions happen at it.
    'barrio-01': (u'Parque Otra Banda', -5, 6, None),
    'barrio-02': (u'Parque Otra Banda', -5, 8, None),
    'barrio-03': (u'Parque Otra Banda', 7, 5, None),
    'barrio-04': (u'Parque Otra Banda', -9, -3, None),
    'barrio-05': (u'Parque Otra Banda', 3, -7, None),
    'barrio-06': (u'Parque Otra Banda', 10, -4, None),
    'barrio-07': (u'Parque Otra Banda', -3, 10, 'bici'),
    'barrio-08': (u'Parque Otra Banda', -7, 12, None),
    'barrio-09': (u'Parque Otra Banda', 12, 7, 'camioneta'),
    'barrio-10': (u'Parque Otra Banda', 5, 13, None),
    'barrio-11': (u'Parque Otra Banda', -12, 4, None),
    'barrio-12': (u'Parque Otra Banda', 9, -9, None),
    'barrio-13': (u'Parque Otra Banda', -6, 10, None),
    'barrio-14': (u'Parque Otra Banda', 2, 3, None),
    # El trabajo: the workshop, out by the stadium.
    'trabajo-01': (u'Estadio Roque Tadeo Zavala', -6, 8, None),
    'trabajo-02': (u'Estadio Roque Tadeo Zavala', 7, 6, 'moto'),
    'trabajo-03': (u'Estadio Roque Tadeo Zavala', 9, 8, None),
    'trabajo-04': (u'Estadio Roque Tadeo Zavala', 5, 10, None),
    'trabajo-05': (u'Estadio Roque Tadeo Zavala', 12, 4, None),
    'trabajo-06': (u'Estadio Roque Tadeo Zavala', -9, 5, None),
    'trabajo-07': (u'Estadio Roque Tadeo Zavala', 3, 12, None),
    'trabajo-08': (u'Estadio Roque Tadeo Zavala', 14, 8, None),
    'trabajo-09': (u'Estadio Roque Tadeo Zavala', 8, -5, None),
    'trabajo-10': (u'Estadio Roque Tadeo Zavala', 11, 11, None),
    # Trámites: the clinic and the hospital, and the offices around them.
    'tramites-01': (u'Hospital Granada', 8, 6, None),
    'tramites-02': (u'Hospital Granada', -7, 5, None),
    'tramites-03': (u'Hospital Granada', 11, -4, None),
    'tramites-04': (u'Hospital Granada', 2, 8, None),
    'tramites-05': (u'Hospital Granada', -10, -5, None),
    'tramites-06': (u'Hospital Granada', 6, -8, None),
    'tramites-07': (u'Hospital Granada', -4, 11, None),
    'tramites-08': (u'Hospital Granada', 13, 3, None),
    'tramites-09': (u'Hospital Granada', -12, 2, None),
    'tramites-10': (u'Hospital Granada', 4, -11, None),
    # El Malecón: the lakefront itself, so these hug the shore.
    'malecon-01': (u'Centro Turistico', -5, 6, None),
    'malecon-02': (u'Centro Turistico', 8, 9, 'lancha'),
    'malecon-03': (u'Centro Turistico', -8, -4, None),
    'malecon-04': (u'Centro Turistico', 3, 12, None),
    'malecon-05': (u'Centro Turistico', 11, -5, None),
    'malecon-06': (u'Centro Turistico', -11, 9, None),
    'malecon-07': (u'Centro Turistico', 14, 4, None),
    'malecon-08': (u'Centro Turistico', -3, -9, 'lancha'),
    # Las fiestas: around the two churches of El Socorro, north of the centre.
    'fiestas-01': (u'Parroquia Nuestra Se\xf1ora del Socorro', -6, 5, None),
    'fiestas-02': (u'Parroquia Nuestra Se\xf1ora del Socorro', 7, 4, None),
    'fiestas-03': (u'Parroquia Nuestra Se\xf1ora del Socorro', -4, -7, None),
    'fiestas-04': (u'Iglesia Vieja Ermita El Socorro', 8, 6, None),
    'fiestas-05': (u'Iglesia Vieja Ermita El Socorro', -7, 5, None),
    'fiestas-06': (u'Iglesia Vieja Ermita El Socorro', 5, -6, None),
    'fiestas-07': (u'Parroquia Nuestra Se\xf1ora del Socorro', 11, -3, None),
    'fiestas-08': (u'Parroquia Nuestra Se\xf1ora del Socorro', 2, 10, None),
    # Afuera: everybody on the road west, heading out. The man with the
    # broken-down car is furthest along it, which is the point of him.
    'afuera-01': (u'Camino a la Laguna', 5, -4, None),
    'afuera-02': (u'Camino a la Laguna', 9, 3, None),
    'afuera-03': (u'Camino a la Laguna', 3, 7, None),
    'afuera-04': (u'Camino a la Laguna', 12, -2, None),
    'afuera-05': (u'Camino a la Laguna', 7, 9, None),
    'afuera-06': (u'Camino a la Laguna', 14, 5, None),
    'afuera-07': (u'Camino a la Laguna', 16, -5, 'camioneta'),
    'afuera-08': (u'Camino a la Laguna', 10, 11, None),
}

# Skin and shirt, drawn deterministically from the id so a face never changes
# between builds. Granada is not a monochrome city and neither is this list.
SKIN = ['#B9825A', '#8A5C3A', '#D8A87C', '#A06E48', '#6E4A30', '#C08E63']
SHIRT = ['#4C7FB5', '#C4685F', '#3E8E8A', '#E3CFA3', '#5B6BA8', '#D89A4E',
         '#7FA05C', '#B0554E']


def pick(seq, key):
    return seq[zlib.crc32(key.encode('utf-8')) % len(seq)]


def scatter(i):
    """A ring of offsets, so unplaced missions do not stack on one tile."""
    ring = [(6, 4), (-7, 5), (5, -6), (-6, -5), (10, 0), (0, 9), (-11, 1),
            (2, -11), (12, 7), (-12, -7), (8, -9), (-9, 8)]
    return ring[i % len(ring)]


APP_PLACE = os.path.join(ROOT, 'docs', 'js', 'game', 'place.js')


def write_app():
    """Where everybody stands, as an ES module for the real app.

    The missions themselves reach the app inside the content pack, like every
    other bit of course content. Placement cannot: it is a fact about the MAP,
    not about the mission, so it lives here beside the map generator and ships
    with the app. A tile number in a mission file would rot the moment the map
    was rebuilt at a different scale.
    """
    d = os.path.dirname(APP_PLACE)
    if not os.path.isdir(d):
        os.makedirs(d)
    rows = {}
    for mid, (at, dx, dy, veh) in sorted(PLACE.items()):
        dx, dy = widen(mid, dx, dy)
        row = {'at': at, 'dx': dx, 'dy': dy}
        if veh:
            row['vehicle'] = veh
        rows[mid] = row
    body = [
        '// Where everybody stands. GENERATED by scripts/game_bake.py -- do not edit.',
        '//',
        '// A real named place from the OSM extract, plus an offset in tiles.',
        '// walkable-and-reachable placement happens at runtime, so these are',
        '// intentions rather than coordinates.',
        '',
        'export const PLACE = ' + json.dumps(rows, ensure_ascii=False,
                                             indent=1, sort_keys=True) + ';',
        '',
        "// Every district's fallback anchor, for anything with no placement.",
        'export const DISTRICT = ' + json.dumps(DISTRICT, ensure_ascii=False,
                                                indent=1, sort_keys=True) + ';',
        '',
    ]
    with io.open(APP_PLACE, 'w', encoding='utf-8', newline=NL) as f:
        f.write(NL.join(body))
    return APP_PLACE


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--content', default=os.path.join(os.path.dirname(ROOT),
                                                      'fluidez-es-ni'))
    ap.add_argument('--report')
    ap.add_argument('--app', action='store_true',
                    help='also write docs/js/game/place.js for the real app')
    a = ap.parse_args()

    gdir = os.path.join(a.content, 'content', 'game')
    if not os.path.isdir(gdir):
        raise SystemExit('no missions at %s -- clone scenicprints/fluidez-es-ni '
                         'beside this repo, or pass --content' % gdir)

    missions, notes = [], []
    unplaced = []
    for i, name in enumerate(sorted(os.listdir(gdir))):
        if not name.endswith('.json'):
            continue
        m = json.load(io.open(os.path.join(gdir, name), encoding='utf-8'))
        mid = m['id']
        if mid in PLACE:
            at, dx, dy, veh = PLACE[mid]
        else:
            at, veh = DISTRICT.get(m.get('district'), u'Parque Central'), None
            dx, dy = scatter(len(unplaced))
            unplaced.append(mid)
        dx, dy = widen(mid, dx, dy)
        row = {
            'id': mid, 'at': at, 'dx': dx, 'dy': dy,
            'name': m['who'], 'quest': m['goal'],
            # What the street tells you, filled in below from the crowd.
            'where': m.get('title', ''),
            # The culture note is the right thing to land on at the end: it is
            # the payoff the mission was written for.
            'done': m.get('culture', ''),
            'idle': m['beats'][0]['es'],
            'skin': pick(SKIN, mid), 'shirt': pick(SHIRT, m['who']),
            'beats': m['beats'],
        }
        if veh:
            row['vehicle'] = veh
            row['driver'] = True
        missions.append(row)

    # the crowd, and what each of them points at
    crowd, points = [], {}
    cdir = os.path.join(gdir, 'crowd')
    if os.path.isdir(cdir):
        for name in sorted(os.listdir(cdir)):
            if not name.endswith('.json'):
                continue
            for j, h in enumerate(json.load(io.open(os.path.join(cdir, name),
                                                    encoding='utf-8'))):
                key = '%s-%d' % (name[:-5], j)
                at = DISTRICT.get(h.get('district'), u'Parque Central')
                dx, dy = scatter(j * 5 + 3)
                crowd.append({
                    'id': 'crowd-' + key, 'crowd': True, 'at': at,
                    'dx': dx + (j % 5) * 3 - 6, 'dy': dy + (j % 3) * 4 - 4,
                    'name': h['kind'], 'says': h['says'], 'en': h['en'],
                    'points_at': h.get('points_at', []),
                    'skin': pick(SKIN, key), 'shirt': pick(SHIRT, h['says']),
                    'beats': [],
                })
                for mid in h.get('points_at', []):
                    points.setdefault(mid, []).append(h)

    # A mission's "where" is whatever the street says about it, because that
    # is the only way anybody finds anything here.
    for m in missions:
        hints = points.get(m['id']) or []
        m['where'] = hints[0]['en'] if hints else u'Ask somebody in the street'
        if not hints:
            notes.append(u'%s: nobody in the crowd points at it' % m['id'])

    for mid in unplaced:
        notes.append(u'%s: no placement, dropped near its district anchor '
                     u'(add it to PLACE in game_bake.py)' % mid)

    blob = (BEGIN + u'\nconst MISSIONS = ' +
            json.dumps(missions, ensure_ascii=False, separators=(',', ':')) +
            u';\nconst CROWD = ' +
            json.dumps(crowd, ensure_ascii=False, separators=(',', ':')) +
            u';\n' + END)

    html = io.open(HTML, encoding='utf-8').read()
    i, j = html.find(BEGIN), html.find(END)
    if i < 0 or j < 0:
        raise SystemExit('no mission markers in granada.html')
    html = html[:i] + blob + html[j + len(END):]
    io.open(HTML, 'w', encoding='utf-8', newline='\n').write(html)

    L = [u'missions  %d baked in, %d beats'
         % (len(missions), sum(len(m['beats']) for m in missions)),
         u'crowd     %d street lines, pointing at %d missions'
         % (len(crowd), len(points)),
         u'vehicles  %d missions happen at one'
         % sum(1 for m in missions if m.get('vehicle')),
         u'placed    %d by hand, %d dropped at a district anchor'
         % (len(missions) - len(unplaced), len(unplaced))]
    if a.app:
        L.append(u'wrote     ' + write_app())
    L += [u'NOTE: ' + n for n in notes] or [u'placement clean']
    out = u'\n'.join(L) + u'\n'
    if a.report:
        io.open(a.report, 'w', encoding='utf-8').write(out)
    print(out.encode('ascii', 'replace').decode('ascii'))


if __name__ == '__main__':
    main()
